#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
    namespace PIOC_per{
        using Addr = Register::Address<0xfffff600,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_pdr{
        using Addr = Register::Address<0xfffff604,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_psr{
        using Addr = Register::Address<0xfffff608,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_oer{
        using Addr = Register::Address<0xfffff610,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_odr{
        using Addr = Register::Address<0xfffff614,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_osr{
        using Addr = Register::Address<0xfffff618,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_ifer{
        using Addr = Register::Address<0xfffff620,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_ifdr{
        using Addr = Register::Address<0xfffff624,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_ifsr{
        using Addr = Register::Address<0xfffff628,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_sodr{
        using Addr = Register::Address<0xfffff630,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_codr{
        using Addr = Register::Address<0xfffff634,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_odsr{
        using Addr = Register::Address<0xfffff638,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_pdsr{
        using Addr = Register::Address<0xfffff63c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_ier{
        using Addr = Register::Address<0xfffff640,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_idr{
        using Addr = Register::Address<0xfffff644,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_imr{
        using Addr = Register::Address<0xfffff648,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_isr{
        using Addr = Register::Address<0xfffff64c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_mder{
        using Addr = Register::Address<0xfffff650,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_mddr{
        using Addr = Register::Address<0xfffff654,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_mdsr{
        using Addr = Register::Address<0xfffff658,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_pudr{
        using Addr = Register::Address<0xfffff660,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_puer{
        using Addr = Register::Address<0xfffff664,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_pusr{
        using Addr = Register::Address<0xfffff668,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_asr{
        using Addr = Register::Address<0xfffff670,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_bsr{
        using Addr = Register::Address<0xfffff674,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_absr{
        using Addr = Register::Address<0xfffff678,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_ower{
        using Addr = Register::Address<0xfffff6a0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_owdr{
        using Addr = Register::Address<0xfffff6a4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_owsr{
        using Addr = Register::Address<0xfffff6a8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOC_delayr0{
        using Addr = Register::Address<0xfffff6c0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOC_delayr1{
        using Addr = Register::Address<0xfffff6c4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOC_delayr2{
        using Addr = Register::Address<0xfffff6c8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOC_delayr3{
        using Addr = Register::Address<0xfffff6cc,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOC_wpmr{
        using Addr = Register::Address<0xfffff6e4,0x000000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPEN; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,8)> WPKEY; 
    }
    namespace PIOC_wpsr{
        using Addr = Register::Address<0xfffff6e8,0xff0000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPVS; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,8)> WPVSRC; 
    }
}
