#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
    namespace PIOD_per{
        using Addr = Register::Address<0xfffff800,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_pdr{
        using Addr = Register::Address<0xfffff804,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_psr{
        using Addr = Register::Address<0xfffff808,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_oer{
        using Addr = Register::Address<0xfffff810,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_odr{
        using Addr = Register::Address<0xfffff814,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_osr{
        using Addr = Register::Address<0xfffff818,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_ifer{
        using Addr = Register::Address<0xfffff820,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_ifdr{
        using Addr = Register::Address<0xfffff824,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_ifsr{
        using Addr = Register::Address<0xfffff828,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_sodr{
        using Addr = Register::Address<0xfffff830,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_codr{
        using Addr = Register::Address<0xfffff834,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_odsr{
        using Addr = Register::Address<0xfffff838,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_pdsr{
        using Addr = Register::Address<0xfffff83c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_ier{
        using Addr = Register::Address<0xfffff840,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_idr{
        using Addr = Register::Address<0xfffff844,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_imr{
        using Addr = Register::Address<0xfffff848,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_isr{
        using Addr = Register::Address<0xfffff84c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_mder{
        using Addr = Register::Address<0xfffff850,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_mddr{
        using Addr = Register::Address<0xfffff854,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_mdsr{
        using Addr = Register::Address<0xfffff858,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_pudr{
        using Addr = Register::Address<0xfffff860,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_puer{
        using Addr = Register::Address<0xfffff864,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_pusr{
        using Addr = Register::Address<0xfffff868,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_asr{
        using Addr = Register::Address<0xfffff870,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_bsr{
        using Addr = Register::Address<0xfffff874,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_absr{
        using Addr = Register::Address<0xfffff878,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_ower{
        using Addr = Register::Address<0xfffff8a0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_owdr{
        using Addr = Register::Address<0xfffff8a4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_owsr{
        using Addr = Register::Address<0xfffff8a8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOD_delayr0{
        using Addr = Register::Address<0xfffff8c0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOD_delayr1{
        using Addr = Register::Address<0xfffff8c4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOD_delayr2{
        using Addr = Register::Address<0xfffff8c8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOD_delayr3{
        using Addr = Register::Address<0xfffff8cc,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOD_wpmr{
        using Addr = Register::Address<0xfffff8e4,0x000000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPEN; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,8)> WPKEY; 
    }
    namespace PIOD_wpsr{
        using Addr = Register::Address<0xfffff8e8,0xff0000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPVS; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,8)> WPVSRC; 
    }
}
