#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
    namespace PIOE_per{
        using Addr = Register::Address<0xfffffa00,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_pdr{
        using Addr = Register::Address<0xfffffa04,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_psr{
        using Addr = Register::Address<0xfffffa08,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_oer{
        using Addr = Register::Address<0xfffffa10,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_odr{
        using Addr = Register::Address<0xfffffa14,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_osr{
        using Addr = Register::Address<0xfffffa18,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_ifer{
        using Addr = Register::Address<0xfffffa20,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_ifdr{
        using Addr = Register::Address<0xfffffa24,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_ifsr{
        using Addr = Register::Address<0xfffffa28,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_sodr{
        using Addr = Register::Address<0xfffffa30,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_codr{
        using Addr = Register::Address<0xfffffa34,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_odsr{
        using Addr = Register::Address<0xfffffa38,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_pdsr{
        using Addr = Register::Address<0xfffffa3c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_ier{
        using Addr = Register::Address<0xfffffa40,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_idr{
        using Addr = Register::Address<0xfffffa44,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_imr{
        using Addr = Register::Address<0xfffffa48,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_isr{
        using Addr = Register::Address<0xfffffa4c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_mder{
        using Addr = Register::Address<0xfffffa50,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_mddr{
        using Addr = Register::Address<0xfffffa54,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_mdsr{
        using Addr = Register::Address<0xfffffa58,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_pudr{
        using Addr = Register::Address<0xfffffa60,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_puer{
        using Addr = Register::Address<0xfffffa64,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_pusr{
        using Addr = Register::Address<0xfffffa68,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_asr{
        using Addr = Register::Address<0xfffffa70,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_bsr{
        using Addr = Register::Address<0xfffffa74,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_absr{
        using Addr = Register::Address<0xfffffa78,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_ower{
        using Addr = Register::Address<0xfffffaa0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_owdr{
        using Addr = Register::Address<0xfffffaa4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_owsr{
        using Addr = Register::Address<0xfffffaa8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOE_delayr0{
        using Addr = Register::Address<0xfffffac0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOE_delayr1{
        using Addr = Register::Address<0xfffffac4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOE_delayr2{
        using Addr = Register::Address<0xfffffac8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOE_delayr3{
        using Addr = Register::Address<0xfffffacc,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOE_wpmr{
        using Addr = Register::Address<0xfffffae4,0x000000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPEN; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,8)> WPKEY; 
    }
    namespace PIOE_wpsr{
        using Addr = Register::Address<0xfffffae8,0xff0000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPVS; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,8)> WPVSRC; 
    }
}
