#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
//None
    namespace Nonetxcontrol{    ///<Transmit Control
        using Addr = Register::Address<0x4003a000,0xd88c001c,0,unsigned>;
        ///DFS Generator Enable. 
        enum class FsgenVal {
            disabled=0x00000000,     ///<Disable the internal DFS generator.
            enabled=0x00000001,     ///<Enable the internal DFS generator.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(0,0),Register::ReadWriteAccess,FsgenVal> fsgen{}; 
        namespace FsgenValC{
            constexpr Register::FieldValue<decltype(fsgen)::Type,FsgenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(fsgen)::Type,FsgenVal::enabled> enabled{};
        }
        ///DFS Synchronize Enable. 
        enum class FssenVal {
            disabled=0x00000000,     ///<The internal DFS generator starts immediately when FSGEN is set to 1.
            enabled=0x00000001,     ///<Synchronize the rising edge of the internally generated WS signal from the DFS generator to the rising edge of the external WS input signal.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(1,1),Register::ReadWriteAccess,FssenVal> fssen{}; 
        namespace FssenValC{
            constexpr Register::FieldValue<decltype(fssen)::Type,FssenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(fssen)::Type,FssenVal::enabled> enabled{};
        }
        ///Transmit Delay Disable. 
        enum class DdisVal {
            inactive=0x00000000,     ///<The first data bit is sent on the second or later rising edge of SCK after WS changes.
            active=0x00000001,     ///<The first data bit is sent on the first rising edge of SCK after WS changes.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(5,5),Register::ReadWriteAccess,DdisVal> ddis{}; 
        namespace DdisValC{
            constexpr Register::FieldValue<decltype(ddis)::Type,DdisVal::inactive> inactive{};
            constexpr Register::FieldValue<decltype(ddis)::Type,DdisVal::active> active{};
        }
        ///Transmit Initial Phase Delay. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(13,6),Register::ReadWriteAccess,unsigned> fsdel{}; 
        ///Transmit Frame Sync Source Select. 
        enum class FssrcselVal {
            fsinExt=0x00000000,     ///<The word select or frame sync is input from the WS pin.
            fsinInt=0x00000001,     ///<The word select or frame sync is input from the internal DFS generator.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(14,14),Register::ReadWriteAccess,FssrcselVal> fssrcsel{}; 
        namespace FssrcselValC{
            constexpr Register::FieldValue<decltype(fssrcsel)::Type,FssrcselVal::fsinExt> fsinExt{};
            constexpr Register::FieldValue<decltype(fssrcsel)::Type,FssrcselVal::fsinInt> fsinInt{};
        }
        ///Transmit Data Fill Select. 
        enum class FillselVal {
            zeros=0x00000000,     ///<Send zeros during unused bit cycles.
            ones=0x00000001,     ///<Send ones during unused bit cycles.
            sign=0x00000002,     ///<Send the sign bit of the current sample (MSB-first format) or last sample (LSB-first format) during unused bit cycles.
            random=0x00000003,     ///<Send pseudo-random data generated by an 8-bit LFSR during unused bit cycles.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(16,15),Register::ReadWriteAccess,FillselVal> fillsel{}; 
        namespace FillselValC{
            constexpr Register::FieldValue<decltype(fillsel)::Type,FillselVal::zeros> zeros{};
            constexpr Register::FieldValue<decltype(fillsel)::Type,FillselVal::ones> ones{};
            constexpr Register::FieldValue<decltype(fillsel)::Type,FillselVal::sign> sign{};
            constexpr Register::FieldValue<decltype(fillsel)::Type,FillselVal::random> random{};
        }
        ///Transmit Data Justification Select. 
        enum class JselVal {
            left=0x00000000,     ///<Use left-justified or I2S-style formats.
            right=0x00000001,     ///<Use right-justified format.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(17,17),Register::ReadWriteAccess,JselVal> jsel{}; 
        namespace JselValC{
            constexpr Register::FieldValue<decltype(jsel)::Type,JselVal::left> left{};
            constexpr Register::FieldValue<decltype(jsel)::Type,JselVal::right> right{};
        }
        ///Transmit WS Inversion Enable. 
        enum class FsinvenVal {
            disabled=0x00000000,     ///<Don't invert the WS signal. Use this setting for I2S format.
            enabled=0x00000001,     ///<Invert the WS signal.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(20,20),Register::ReadWriteAccess,FsinvenVal> fsinven{}; 
        namespace FsinvenValC{
            constexpr Register::FieldValue<decltype(fsinven)::Type,FsinvenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(fsinven)::Type,FsinvenVal::enabled> enabled{};
        }
        ///Transmit SCK Inversion Enable. 
        enum class SclkinvenVal {
            disabled=0x00000000,     ///<Do not invert the transmitter bit clock.
            enabled=0x00000001,     ///<Invert the transmitter bit clock.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(21,21),Register::ReadWriteAccess,SclkinvenVal> sclkinven{}; 
        namespace SclkinvenValC{
            constexpr Register::FieldValue<decltype(sclkinven)::Type,SclkinvenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(sclkinven)::Type,SclkinvenVal::enabled> enabled{};
        }
        ///Transmit Order. 
        enum class OrderVal {
            leftRight=0x00000000,     ///<Left sample transmitted first, right sample transmitted second. Use this setting for I2S format.
            rightLeft=0x00000001,     ///<Right sample transmitted first, left sample transmitted second.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(22,22),Register::ReadWriteAccess,OrderVal> order{}; 
        namespace OrderValC{
            constexpr Register::FieldValue<decltype(order)::Type,OrderVal::leftRight> leftRight{};
            constexpr Register::FieldValue<decltype(order)::Type,OrderVal::rightLeft> rightLeft{};
        }
        ///Transmit Mono Bit-Width Select. 
        enum class MbselVal {
            v8bits=0x00000000,     ///<8 bits are sent per mono sample.
            v9bits=0x00000001,     ///<9 bits are sent per mono sample.
            v16bits=0x00000002,     ///<16 bits are sent per mono sample.
            v24bits=0x00000003,     ///<24 bits are sent per mono sample.
            v32bits=0x00000004,     ///<32 bits are sent per mono sample.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(26,24),Register::ReadWriteAccess,MbselVal> mbsel{}; 
        namespace MbselValC{
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v8bits> v8bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v9bits> v9bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v16bits> v16bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v24bits> v24bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v32bits> v32bits{};
        }
        ///Transmitter Enable. 
        enum class TxenVal {
            disabled=0x00000000,     ///<Disable the I2S transmitter.
            enabled=0x00000001,     ///<Enable the I2S transmitter.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(29,29),Register::ReadWriteAccess,TxenVal> txen{}; 
        namespace TxenValC{
            constexpr Register::FieldValue<decltype(txen)::Type,TxenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txen)::Type,TxenVal::enabled> enabled{};
        }
    }
    namespace Nonetxmode{    ///<Transmit Mode
        using Addr = Register::Address<0x4003a010,0xf0000000,0,unsigned>;
        ///Transmit Clock Cycle Select. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(11,0),Register::ReadWriteAccess,unsigned> cycle{}; 
        ///Transmit Start Control. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(19,12),Register::ReadWriteAccess,unsigned> start{}; 
        ///Transmit Drive Select. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(24,20),Register::ReadWriteAccess,unsigned> slots{}; 
        ///Transmit Drive Early Disable. 
        enum class DedisVal {
            inactive=0x00000000,     ///<Drive the output during every cycle of the transmitter's assigned slot(s), including the last clock cycle.
            active=0x00000001,     ///<Drive the output for every cycle of the transmitter's assigned slot(s), except for the last clock cycle of the last slot.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(25,25),Register::ReadWriteAccess,DedisVal> dedis{}; 
        namespace DedisValC{
            constexpr Register::FieldValue<decltype(dedis)::Type,DedisVal::inactive> inactive{};
            constexpr Register::FieldValue<decltype(dedis)::Type,DedisVal::active> active{};
        }
        ///Transmit Drive Inactive Mode. 
        enum class DimdVal {
            zero=0x00000000,     ///<Drive zero on the data output pin during non-active slots.
            highZ=0x00000001,     ///<Don't drive the data output pin. The data output pin is tristated.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(26,26),Register::ReadWriteAccess,DimdVal> dimd{}; 
        namespace DimdValC{
            constexpr Register::FieldValue<decltype(dimd)::Type,DimdVal::zero> zero{};
            constexpr Register::FieldValue<decltype(dimd)::Type,DimdVal::highZ> highZ{};
        }
        ///Transmit Time Division Multiplexing Enable. 
        enum class TdmenVal {
            disabled=0x00000000,     ///<Disable the time division multiplexing (TDM) feature.
            enabled=0x00000001,     ///<Enable the time division multiplexing (TDM) feature.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(27,27),Register::ReadWriteAccess,TdmenVal> tdmen{}; 
        namespace TdmenValC{
            constexpr Register::FieldValue<decltype(tdmen)::Type,TdmenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(tdmen)::Type,TdmenVal::enabled> enabled{};
        }
    }
    namespace Nonefsduty{    ///<Frame Sync Duty Cycle
        using Addr = Register::Address<0x4003a020,0x00000000,0,unsigned>;
        ///Frame Sync Low Time. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(15,0),Register::ReadWriteAccess,unsigned> fslow{}; 
        ///Frame Sync High Time. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(31,16),Register::ReadWriteAccess,unsigned> fshigh{}; 
    }
    namespace Nonerxcontrol{    ///<Receive Control
        using Addr = Register::Address<0x4003a030,0xffcc4400,0,unsigned>;
        ///Receive Initial Phase Delay. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(7,0),Register::ReadWriteAccess,unsigned> fsdel{}; 
        ///Receive Data Justification. 
        enum class JselVal {
            left=0x00000000,     ///<Use left-justified or I2S-style formats.
            right=0x00000001,     ///<Use right-justified format.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(8,8),Register::ReadWriteAccess,JselVal> jsel{}; 
        namespace JselValC{
            constexpr Register::FieldValue<decltype(jsel)::Type,JselVal::left> left{};
            constexpr Register::FieldValue<decltype(jsel)::Type,JselVal::right> right{};
        }
        ///Receive Delay Disable. 
        enum class DdisVal {
            inactive=0x00000000,     ///<The first data bit is captured on the second or later rising edge of SCK after WS changes.
            active=0x00000001,     ///<The first data bit is captured by the receiver on the first rising edge of SCK after WS changes.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(9,9),Register::ReadWriteAccess,DdisVal> ddis{}; 
        namespace DdisValC{
            constexpr Register::FieldValue<decltype(ddis)::Type,DdisVal::inactive> inactive{};
            constexpr Register::FieldValue<decltype(ddis)::Type,DdisVal::active> active{};
        }
        ///Receive WS Inversion Enable. 
        enum class FsinvenVal {
            disabled=0x00000000,     ///<Don't invert the WS signal. Use this setting for I2S format.
            enabled=0x00000001,     ///<Invert the WS signal.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(11,11),Register::ReadWriteAccess,FsinvenVal> fsinven{}; 
        namespace FsinvenValC{
            constexpr Register::FieldValue<decltype(fsinven)::Type,FsinvenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(fsinven)::Type,FsinvenVal::enabled> enabled{};
        }
        ///Receive SCK Inversion Enable. 
        enum class SclkinvenVal {
            disabled=0x00000000,     ///<Do not invert the receiver bit clock.
            enabled=0x00000001,     ///<Invert the receiver bit clock.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(12,12),Register::ReadWriteAccess,SclkinvenVal> sclkinven{}; 
        namespace SclkinvenValC{
            constexpr Register::FieldValue<decltype(sclkinven)::Type,SclkinvenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(sclkinven)::Type,SclkinvenVal::enabled> enabled{};
        }
        ///Receive Order. 
        enum class OrderVal {
            leftRight=0x00000000,     ///<Left sample received first, right sample received second. Use this setting for I2S format.
            rightLeft=0x00000001,     ///<Right sample received first, left sample received second.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(13,13),Register::ReadWriteAccess,OrderVal> order{}; 
        namespace OrderValC{
            constexpr Register::FieldValue<decltype(order)::Type,OrderVal::leftRight> leftRight{};
            constexpr Register::FieldValue<decltype(order)::Type,OrderVal::rightLeft> rightLeft{};
        }
        ///Receive Mono Bit-Width Select. 
        enum class MbselVal {
            v8bits=0x00000000,     ///<8 bits are received per mono sample.
            v9bits=0x00000001,     ///<9 bits are received per mono sample.
            v16bits=0x00000002,     ///<16 bits are received per mono sample.
            v24bits=0x00000003,     ///<24 bits are received per mono sample.
            v32bits=0x00000004,     ///<32 bits are received per mono sample.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(17,15),Register::ReadWriteAccess,MbselVal> mbsel{}; 
        namespace MbselValC{
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v8bits> v8bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v9bits> v9bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v16bits> v16bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v24bits> v24bits{};
            constexpr Register::FieldValue<decltype(mbsel)::Type,MbselVal::v32bits> v32bits{};
        }
        ///Receive Frame Sync Source Select. 
        enum class FssrcselVal {
            fsinExt=0x00000000,     ///<The word select or frame sync is input from the WS pin.
            fsinInt=0x00000001,     ///<The word select or frame sync is input from the internal DFS generator.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(20,20),Register::ReadWriteAccess,FssrcselVal> fssrcsel{}; 
        namespace FssrcselValC{
            constexpr Register::FieldValue<decltype(fssrcsel)::Type,FssrcselVal::fsinExt> fsinExt{};
            constexpr Register::FieldValue<decltype(fssrcsel)::Type,FssrcselVal::fsinInt> fsinInt{};
        }
        ///Receive Enable. 
        enum class RxenVal {
            disabled=0x00000000,     ///<Disable the I2S receiver.
            enabled=0x00000001,     ///<Enable the I2S receiver.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(21,21),Register::ReadWriteAccess,RxenVal> rxen{}; 
        namespace RxenValC{
            constexpr Register::FieldValue<decltype(rxen)::Type,RxenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxen)::Type,RxenVal::enabled> enabled{};
        }
    }
    namespace Nonerxmode{    ///<Receive Mode
        using Addr = Register::Address<0x4003a040,0xf4000000,0,unsigned>;
        ///Receive Clock Cycle Select. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(11,0),Register::ReadWriteAccess,unsigned> cycle{}; 
        ///Receive Start Control. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(19,12),Register::ReadWriteAccess,unsigned> start{}; 
        ///Receive Drive Select. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(25,20),Register::ReadWriteAccess,unsigned> slots{}; 
        ///Receive Time Division Multiplexing Enable. 
        enum class TdmenVal {
            disabled=0x00000000,     ///<Disable the time division multiplexing (TDM) feature.
            enabled=0x00000001,     ///<Enable the time division multiplexing (TDM) feature.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(27,27),Register::ReadWriteAccess,TdmenVal> tdmen{}; 
        namespace TdmenValC{
            constexpr Register::FieldValue<decltype(tdmen)::Type,TdmenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(tdmen)::Type,TdmenVal::enabled> enabled{};
        }
    }
    namespace Noneclkcontrol{    ///<Clock Control
        using Addr = Register::Address<0x4003a050,0xf0000000,0,unsigned>;
        ///Clock Divider Integer Value. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(9,0),Register::ReadWriteAccess,unsigned> intdiv{}; 
        ///Clock Divider Fractional Value. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(17,10),Register::ReadWriteAccess,unsigned> fracdiv{}; 
        ///Duty Cycle Adjustment Mode. 
        enum class DutymdVal {
            more=0x00000000,     ///<When the division is fractional, the clock high time will be greater than 50% (by half of the source clock period).
            less=0x00000001,     ///<When the division is fractional, the clock low time will be greater than 50% (by half of the source clock period).
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(18,18),Register::ReadWriteAccess,DutymdVal> dutymd{}; 
        namespace DutymdValC{
            constexpr Register::FieldValue<decltype(dutymd)::Type,DutymdVal::more> more{};
            constexpr Register::FieldValue<decltype(dutymd)::Type,DutymdVal::less> less{};
        }
        ///Clock Divider Update. 
        enum class ClkupdVal {
            update=0x00000001,     ///<Update the clock divider with new values of INTDIV, FRACDIV, and DIVEN.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(19,19),Register::ReadWriteAccess,ClkupdVal> clkupd{}; 
        namespace ClkupdValC{
            constexpr Register::FieldValue<decltype(clkupd)::Type,ClkupdVal::update> update{};
        }
        ///Clock Divider Enable. 
        enum class DivenVal {
            disabled=0x00000000,     ///<Disable the clock divider.
            enabled=0x00000001,     ///<Enable the clock divider.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(20,20),Register::ReadWriteAccess,DivenVal> diven{}; 
        namespace DivenValC{
            constexpr Register::FieldValue<decltype(diven)::Type,DivenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(diven)::Type,DivenVal::enabled> enabled{};
        }
        ///Transmit Clock Select. 
        enum class TxclkselVal {
            internal=0x00000000,     ///<The I2S transmitter is clocked from the internal clock divider.
            external=0x00000001,     ///<The I2S transmitter is clocked from the SCK pin.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(21,21),Register::ReadWriteAccess,TxclkselVal> txclksel{}; 
        namespace TxclkselValC{
            constexpr Register::FieldValue<decltype(txclksel)::Type,TxclkselVal::internal> internal{};
            constexpr Register::FieldValue<decltype(txclksel)::Type,TxclkselVal::external> external{};
        }
        ///Receive Clock Select. 
        enum class RxclkselVal {
            internal=0x00000000,     ///<The I2S receiver is clocked from the internal clock divider.
            external=0x00000001,     ///<The I2S receiver is clocked from the SCK pin.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(22,22),Register::ReadWriteAccess,RxclkselVal> rxclksel{}; 
        namespace RxclkselValC{
            constexpr Register::FieldValue<decltype(rxclksel)::Type,RxclkselVal::internal> internal{};
            constexpr Register::FieldValue<decltype(rxclksel)::Type,RxclkselVal::external> external{};
        }
        ///I2S Module Reset. 
        enum class ResetVal {
            active=0x00000001,     ///<Reset the I2S module.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(23,23),Register::ReadWriteAccess,ResetVal> reset{}; 
        namespace ResetValC{
            constexpr Register::FieldValue<decltype(reset)::Type,ResetVal::active> active{};
        }
        ///Receive Clock Enable. 
        enum class RxclkenVal {
            disabled=0x00000000,     ///<Disable the I2S receiver clock.
            enabled=0x00000001,     ///<Enable the I2S receiver clock.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(24,24),Register::ReadWriteAccess,RxclkenVal> rxclken{}; 
        namespace RxclkenValC{
            constexpr Register::FieldValue<decltype(rxclken)::Type,RxclkenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxclken)::Type,RxclkenVal::enabled> enabled{};
        }
        ///Transmit Clock Enable. 
        enum class TxclkenVal {
            disabled=0x00000000,     ///<Disable the I2S transmitter clock.
            enabled=0x00000001,     ///<Enable the I2S transmitter clock.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(25,25),Register::ReadWriteAccess,TxclkenVal> txclken{}; 
        namespace TxclkenValC{
            constexpr Register::FieldValue<decltype(txclken)::Type,TxclkenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txclken)::Type,TxclkenVal::enabled> enabled{};
        }
        ///Receive SCK Mode. 
        enum class RxsclkmdVal {
            sckOutput=0x00000000,     ///<The I2S receiver SCK signal is an output.
            sckInput=0x00000001,     ///<The I2S receiver SCK signal is an input.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(26,26),Register::ReadWriteAccess,RxsclkmdVal> rxsclkmd{}; 
        namespace RxsclkmdValC{
            constexpr Register::FieldValue<decltype(rxsclkmd)::Type,RxsclkmdVal::sckOutput> sckOutput{};
            constexpr Register::FieldValue<decltype(rxsclkmd)::Type,RxsclkmdVal::sckInput> sckInput{};
        }
        ///Transmit SCK Mode. 
        enum class TxsclkmdVal {
            sckOutput=0x00000000,     ///<The I2S transmitter SCK signal is an output.
            sckInput=0x00000001,     ///<The I2S transmitter SCK signal is an input.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(27,27),Register::ReadWriteAccess,TxsclkmdVal> txsclkmd{}; 
        namespace TxsclkmdValC{
            constexpr Register::FieldValue<decltype(txsclkmd)::Type,TxsclkmdVal::sckOutput> sckOutput{};
            constexpr Register::FieldValue<decltype(txsclkmd)::Type,TxsclkmdVal::sckInput> sckInput{};
        }
    }
    namespace Nonetxfifo{    ///<Transmit Data FIFO
        using Addr = Register::Address<0x4003a060,0x00000000,0,unsigned>;
        ///Transmit Data FIFO. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(31,0),Register::ReadWriteAccess,unsigned> txfifo{}; 
    }
    namespace Nonerxfifo{    ///<Receive Data FIFO
        using Addr = Register::Address<0x4003a070,0x00000000,0,unsigned>;
        ///Receive Data FIFO. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(31,0),Register::ReadWriteAccess,unsigned> rxfifo{}; 
    }
    namespace Nonefifostatus{    ///<FIFO Status
        using Addr = Register::Address<0x4003a080,0xfff0fff0,0,unsigned>;
        ///Transmit FIFO Status. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,0),Register::ReadWriteAccess,unsigned> txfifonum{}; 
        ///Receive FIFO Status. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(19,16),Register::ReadWriteAccess,unsigned> rxfifonum{}; 
    }
    namespace Nonefifocontrol{    ///<FIFO Control
        using Addr = Register::Address<0x4003a090,0xff90fff0,0,unsigned>;
        ///Transmit FIFO Low Watermark. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,0),Register::ReadWriteAccess,unsigned> txfifowm{}; 
        ///Receive FIFO High Watermark. 
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(19,16),Register::ReadWriteAccess,unsigned> rxfifowm{}; 
        ///Transmit FIFO Flush. 
        enum class TxfifoflVal {
            set=0x00000001,     ///<Flush the I2S transmitter FIFO.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(21,21),Register::ReadWriteAccess,TxfifoflVal> txfifofl{}; 
        namespace TxfifoflValC{
            constexpr Register::FieldValue<decltype(txfifofl)::Type,TxfifoflVal::set> set{};
        }
        ///Receive FIFO Flush. 
        enum class RxfifoflVal {
            set=0x00000001,     ///<Flush the I2S receiver FIFO.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(22,22),Register::ReadWriteAccess,RxfifoflVal> rxfifofl{}; 
        namespace RxfifoflValC{
            constexpr Register::FieldValue<decltype(rxfifofl)::Type,RxfifoflVal::set> set{};
        }
    }
    namespace Noneintcontrol{    ///<Interrupt Control
        using Addr = Register::Address<0x4003a0a0,0xfffffff0,0,unsigned>;
        ///Transmit Underflow Interrupt Enable. 
        enum class TxufienVal {
            disabled=0x00000000,     ///<Disable the transmit underflow interrupt.
            enabled=0x00000001,     ///<Enable the transmit underflow interrupt.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(0,0),Register::ReadWriteAccess,TxufienVal> txufien{}; 
        namespace TxufienValC{
            constexpr Register::FieldValue<decltype(txufien)::Type,TxufienVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txufien)::Type,TxufienVal::enabled> enabled{};
        }
        ///Receive Overflow Interrupt Enable. 
        enum class RxofienVal {
            disabled=0x00000000,     ///<Disable the receive overflow interrupt.
            enabled=0x00000001,     ///<Enable the receive overflow interrupt.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(1,1),Register::ReadWriteAccess,RxofienVal> rxofien{}; 
        namespace RxofienValC{
            constexpr Register::FieldValue<decltype(rxofien)::Type,RxofienVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxofien)::Type,RxofienVal::enabled> enabled{};
        }
        ///Transmit FIFO Low Watermark Interrupt Enable. 
        enum class TxlwmienVal {
            disabled=0x00000000,     ///<Disable the transmit FIFO low watermark interrupt.
            enabled=0x00000001,     ///<Enable the transmit FIFO low watermark interrupt.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(2,2),Register::ReadWriteAccess,TxlwmienVal> txlwmien{}; 
        namespace TxlwmienValC{
            constexpr Register::FieldValue<decltype(txlwmien)::Type,TxlwmienVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txlwmien)::Type,TxlwmienVal::enabled> enabled{};
        }
        ///Receive FIFO High Watermark Interrupt Enable. 
        enum class RxhwmienVal {
            disabled=0x00000000,     ///<Disable the receive FIFO high watermark interrupt.
            enabled=0x00000001,     ///<Enable the receive FIFO high watermark interrupt.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,3),Register::ReadWriteAccess,RxhwmienVal> rxhwmien{}; 
        namespace RxhwmienValC{
            constexpr Register::FieldValue<decltype(rxhwmien)::Type,RxhwmienVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxhwmien)::Type,RxhwmienVal::enabled> enabled{};
        }
    }
    namespace Nonestatus{    ///<Module Status
        using Addr = Register::Address<0x4003a0b0,0xfffffc00,0,unsigned>;
        ///Transmit Underflow Interrupt Flag. 
        enum class TxufiVal {
            notSet=0x00000000,     ///<A transmit underflow has not occurred.
            set=0x00000001,     ///<A transmit underflow occurred.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(0,0),Register::ReadWriteAccess,TxufiVal> txufi{}; 
        namespace TxufiValC{
            constexpr Register::FieldValue<decltype(txufi)::Type,TxufiVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(txufi)::Type,TxufiVal::set> set{};
        }
        ///Receive Overflow Interrupt Flag. 
        enum class RxofiVal {
            notSet=0x00000000,     ///<A receive overflow has not occurred.
            set=0x00000001,     ///<A receive overflow occurred.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(1,1),Register::ReadWriteAccess,RxofiVal> rxofi{}; 
        namespace RxofiValC{
            constexpr Register::FieldValue<decltype(rxofi)::Type,RxofiVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(rxofi)::Type,RxofiVal::set> set{};
        }
        ///Transmit FIFO Low Watermark Interrupt Flag. 
        enum class TxlwmiVal {
            notSet=0x00000000,     ///<Transmit FIFO level is above the low watermark.
            set=0x00000001,     ///<Transmit FIFO level is at or below the low watermark.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(2,2),Register::ReadWriteAccess,TxlwmiVal> txlwmi{}; 
        namespace TxlwmiValC{
            constexpr Register::FieldValue<decltype(txlwmi)::Type,TxlwmiVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(txlwmi)::Type,TxlwmiVal::set> set{};
        }
        ///Receive FIFO High Watermark Interrupt Flag. 
        enum class RxhwmiVal {
            notSet=0x00000000,     ///<Receive FIFO level is below the high watermark.
            set=0x00000001,     ///<Receive FIFO level is at or above the high watermark.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,3),Register::ReadWriteAccess,RxhwmiVal> rxhwmi{}; 
        namespace RxhwmiValC{
            constexpr Register::FieldValue<decltype(rxhwmi)::Type,RxhwmiVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(rxhwmi)::Type,RxhwmiVal::set> set{};
        }
        ///Clock Divider Busy Flag. 
        enum class CdbusyfVal {
            notBusy=0x00000000,     ///<The divider is not busy and an update is not pending.
            busy=0x00000001,     ///<The divider is busy and an update is pending.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(4,4),Register::ReadWriteAccess,CdbusyfVal> cdbusyf{}; 
        namespace CdbusyfValC{
            constexpr Register::FieldValue<decltype(cdbusyf)::Type,CdbusyfVal::notBusy> notBusy{};
            constexpr Register::FieldValue<decltype(cdbusyf)::Type,CdbusyfVal::busy> busy{};
        }
        ///Clock Divider Counter Status. 
        enum class CdstsVal {
            running=0x00000000,     ///<Divided clock output is running.
            halted=0x00000001,     ///<Divided clock output is halted.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(5,5),Register::ReadWriteAccess,CdstsVal> cdsts{}; 
        namespace CdstsValC{
            constexpr Register::FieldValue<decltype(cdsts)::Type,CdstsVal::running> running{};
            constexpr Register::FieldValue<decltype(cdsts)::Type,CdstsVal::halted> halted{};
        }
        ///Transmit Clock Select Ready Flag. 
        enum class TxclkselrfVal {
            notSet=0x00000000,     ///<The transmit clock is not synchronized.
            set=0x00000001,     ///<The transmit clock is synchronized and the transmitter is ready to send data.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(6,6),Register::ReadWriteAccess,TxclkselrfVal> txclkselrf{}; 
        namespace TxclkselrfValC{
            constexpr Register::FieldValue<decltype(txclkselrf)::Type,TxclkselrfVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(txclkselrf)::Type,TxclkselrfVal::set> set{};
        }
        ///Receive Clock Select Ready Flag. 
        enum class RxclkselrfVal {
            notSet=0x00000000,     ///<The receive clock is not synchronized.
            set=0x00000001,     ///<The receive clock is synchronized and the receiver is ready to accept data.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(7,7),Register::ReadWriteAccess,RxclkselrfVal> rxclkselrf{}; 
        namespace RxclkselrfValC{
            constexpr Register::FieldValue<decltype(rxclkselrf)::Type,RxclkselrfVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(rxclkselrf)::Type,RxclkselrfVal::set> set{};
        }
        ///Transmit Clock Enable Ready Flag. 
        enum class TxclkenrfVal {
            notSet=0x00000000,     ///<The transmit clock is not synchronized.
            set=0x00000001,     ///<The transmit clock is synchronized and the transmitter is ready to send data.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(8,8),Register::ReadWriteAccess,TxclkenrfVal> txclkenrf{}; 
        namespace TxclkenrfValC{
            constexpr Register::FieldValue<decltype(txclkenrf)::Type,TxclkenrfVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(txclkenrf)::Type,TxclkenrfVal::set> set{};
        }
        ///Receive Clock Enable Ready Flag. 
        enum class RxclkenrfVal {
            notSet=0x00000000,     ///<The receive clock is not synchronized.
            set=0x00000001,     ///<The receive clock is synchronized and the receiver is ready to accept data.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(9,9),Register::ReadWriteAccess,RxclkenrfVal> rxclkenrf{}; 
        namespace RxclkenrfValC{
            constexpr Register::FieldValue<decltype(rxclkenrf)::Type,RxclkenrfVal::notSet> notSet{};
            constexpr Register::FieldValue<decltype(rxclkenrf)::Type,RxclkenrfVal::set> set{};
        }
    }
    namespace Nonedmacontrol{    ///<DMA Control
        using Addr = Register::Address<0x4003a0c0,0xfffffff0,0,unsigned>;
        ///Transmit DMA Enable. 
        enum class TxdmaenVal {
            disabled=0x00000000,     ///<Disable transmitter DMA data requests.
            enabled=0x00000001,     ///<Enable transmitter DMA data requests.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(0,0),Register::ReadWriteAccess,TxdmaenVal> txdmaen{}; 
        namespace TxdmaenValC{
            constexpr Register::FieldValue<decltype(txdmaen)::Type,TxdmaenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txdmaen)::Type,TxdmaenVal::enabled> enabled{};
        }
        ///Receive DMA Enable. 
        enum class RxdmaenVal {
            disabled=0x00000000,     ///<Disable receiver DMA data transfer requests.
            enabled=0x00000001,     ///<Enable receiver DMA data transfer requests.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(1,1),Register::ReadWriteAccess,RxdmaenVal> rxdmaen{}; 
        namespace RxdmaenValC{
            constexpr Register::FieldValue<decltype(rxdmaen)::Type,RxdmaenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxdmaen)::Type,RxdmaenVal::enabled> enabled{};
        }
        ///Transmit DMA Burst Mode. 
        enum class TxdmabmdVal {
            oneWord=0x00000000,     ///<The transmitter transmits one word at a time. Whenever there is any room in the transmit FIFO, a single word burst DMA data request is generated.
            fourWords=0x00000001,     ///<The transmitter transmits four words at a time. Whenever the FIFO depth drops below five, a DMA burst request is generated for four words.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(2,2),Register::ReadWriteAccess,TxdmabmdVal> txdmabmd{}; 
        namespace TxdmabmdValC{
            constexpr Register::FieldValue<decltype(txdmabmd)::Type,TxdmabmdVal::oneWord> oneWord{};
            constexpr Register::FieldValue<decltype(txdmabmd)::Type,TxdmabmdVal::fourWords> fourWords{};
        }
        ///Receive DMA Burst Mode. 
        enum class RxdmabmdVal {
            oneWord=0x00000000,     ///<The receiver receives one word at a time. Whenever there is at least one word in the receive FIFO, a single word burst DMA request is generated.
            fourWords=0x00000001,     ///<The receiver receives four words at a time. Whenever the FIFO depth rises above three, a DMA burst request is generated for four words.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,3),Register::ReadWriteAccess,RxdmabmdVal> rxdmabmd{}; 
        namespace RxdmabmdValC{
            constexpr Register::FieldValue<decltype(rxdmabmd)::Type,RxdmabmdVal::oneWord> oneWord{};
            constexpr Register::FieldValue<decltype(rxdmabmd)::Type,RxdmabmdVal::fourWords> fourWords{};
        }
    }
    namespace Nonedbgcontrol{    ///<Debug Control
        using Addr = Register::Address<0x4003a0d0,0xfffffff0,0,unsigned>;
        ///I2S Transmit DMA Debug Halt Enable. 
        enum class TxdbghenVal {
            disabled=0x00000000,     ///<Transmit DMA requests continue while the core is debug mode.
            enabled=0x00000001,     ///<Transmit DMA requests stop while the core is debug mode.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(0,0),Register::ReadWriteAccess,TxdbghenVal> txdbghen{}; 
        namespace TxdbghenValC{
            constexpr Register::FieldValue<decltype(txdbghen)::Type,TxdbghenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(txdbghen)::Type,TxdbghenVal::enabled> enabled{};
        }
        ///I2S Receive DMA Debug Halt Enable. 
        enum class RxdbghenVal {
            disabled=0x00000000,     ///<Receive DMA requests continue while the core is debug mode.
            enabled=0x00000001,     ///<Receive DMA requests stop while the core is debug mode.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(1,1),Register::ReadWriteAccess,RxdbghenVal> rxdbghen{}; 
        namespace RxdbghenValC{
            constexpr Register::FieldValue<decltype(rxdbghen)::Type,RxdbghenVal::disabled> disabled{};
            constexpr Register::FieldValue<decltype(rxdbghen)::Type,RxdbghenVal::enabled> enabled{};
        }
        ///I2S Transmit Debug Mode. 
        enum class TxdbgmdVal {
            run=0x00000000,     ///<The clock to the I2S transmitter is active in debug mode.
            halt=0x00000001,     ///<The clock to the I2S transmitter is not active in debug mode. The clock divider keeps running and the clock will be disabled when two samples are ready to be sent by the transmitter.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(2,2),Register::ReadWriteAccess,TxdbgmdVal> txdbgmd{}; 
        namespace TxdbgmdValC{
            constexpr Register::FieldValue<decltype(txdbgmd)::Type,TxdbgmdVal::run> run{};
            constexpr Register::FieldValue<decltype(txdbgmd)::Type,TxdbgmdVal::halt> halt{};
        }
        ///I2S Receive Debug Mode. 
        enum class RxdbgmdVal {
            run=0x00000000,     ///<The clock to the I2S receiver is active in debug mode.
            halt=0x00000001,     ///<The clock to the I2S receiver is not active in debug mode. The clock divider keeps running and the clock will be disabled when two samples are captured in the receiver.
        };
        constexpr Register::FieldLocation<Addr,Register::maskFromRange(3,3),Register::ReadWriteAccess,RxdbgmdVal> rxdbgmd{}; 
        namespace RxdbgmdValC{
            constexpr Register::FieldValue<decltype(rxdbgmd)::Type,RxdbgmdVal::run> run{};
            constexpr Register::FieldValue<decltype(rxdbgmd)::Type,RxdbgmdVal::halt> halt{};
        }
    }
}
