#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
    namespace Nonectrl{
        using Addr = Register::Address<0x400a8000,0xfffffff8>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> INT; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> COMB; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> TRIG; 
    }
    namespace Noneport_pol0{
        using Addr = Register::Address<0x400a8020,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> POL0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> POL1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> POL2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> POL3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> POL4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> POL5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> POL6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> POL7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> POL8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> POL9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> POL10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> POL11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> POL12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> POL13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> POL14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> POL15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> POL16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> POL17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> POL18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> POL19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> POL20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> POL21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> POL22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> POL23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> POL24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> POL25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> POL26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> POL27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> POL28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> POL29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> POL30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> POL31; 
    }
    namespace Noneport_pol1{
        using Addr = Register::Address<0x400a8024,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> POL0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> POL1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> POL2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> POL3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> POL4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> POL5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> POL6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> POL7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> POL8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> POL9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> POL10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> POL11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> POL12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> POL13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> POL14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> POL15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> POL16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> POL17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> POL18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> POL19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> POL20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> POL21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> POL22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> POL23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> POL24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> POL25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> POL26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> POL27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> POL28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> POL29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> POL30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> POL31; 
    }
    namespace Noneport_pol2{
        using Addr = Register::Address<0x400a8028,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> POL0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> POL1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> POL2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> POL3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> POL4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> POL5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> POL6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> POL7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> POL8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> POL9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> POL10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> POL11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> POL12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> POL13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> POL14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> POL15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> POL16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> POL17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> POL18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> POL19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> POL20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> POL21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> POL22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> POL23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> POL24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> POL25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> POL26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> POL27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> POL28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> POL29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> POL30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> POL31; 
    }
    namespace Noneport_ena0{
        using Addr = Register::Address<0x400a8040,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> ENA0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> ENA1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> ENA2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> ENA3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> ENA4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> ENA5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> ENA6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> ENA7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> ENA8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> ENA9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> ENA10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> ENA11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> ENA12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> ENA13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> ENA14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> ENA15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> ENA16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> ENA17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> ENA18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> ENA19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> ENA20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> ENA21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> ENA22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> ENA23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> ENA24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> ENA25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> ENA26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> ENA27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> ENA28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> ENA29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> ENA30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> ENA31; 
    }
    namespace Noneport_ena1{
        using Addr = Register::Address<0x400a8044,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> ENA0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> ENA1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> ENA2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> ENA3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> ENA4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> ENA5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> ENA6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> ENA7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> ENA8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> ENA9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> ENA10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> ENA11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> ENA12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> ENA13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> ENA14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> ENA15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> ENA16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> ENA17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> ENA18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> ENA19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> ENA20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> ENA21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> ENA22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> ENA23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> ENA24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> ENA25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> ENA26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> ENA27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> ENA28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> ENA29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> ENA30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> ENA31; 
    }
    namespace Noneport_ena2{
        using Addr = Register::Address<0x400a8048,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> ENA0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> ENA1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> ENA2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> ENA3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> ENA4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> ENA5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> ENA6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> ENA7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> ENA8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> ENA9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> ENA10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> ENA11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> ENA12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> ENA13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> ENA14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> ENA15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> ENA16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> ENA17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> ENA18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> ENA19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> ENA20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> ENA21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> ENA22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> ENA23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> ENA24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> ENA25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> ENA26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> ENA27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> ENA28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> ENA29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> ENA30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> ENA31; 
    }
}
