#pragma once 
#include "Register/Utility.hpp"
namespace Kvasir {
    namespace PIOA_per{
        using Addr = Register::Address<0xfffff200,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_pdr{
        using Addr = Register::Address<0xfffff204,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_psr{
        using Addr = Register::Address<0xfffff208,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_oer{
        using Addr = Register::Address<0xfffff210,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_odr{
        using Addr = Register::Address<0xfffff214,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_osr{
        using Addr = Register::Address<0xfffff218,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_ifer{
        using Addr = Register::Address<0xfffff220,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_ifdr{
        using Addr = Register::Address<0xfffff224,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_ifsr{
        using Addr = Register::Address<0xfffff228,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_sodr{
        using Addr = Register::Address<0xfffff230,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_codr{
        using Addr = Register::Address<0xfffff234,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_odsr{
        using Addr = Register::Address<0xfffff238,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_pdsr{
        using Addr = Register::Address<0xfffff23c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_ier{
        using Addr = Register::Address<0xfffff240,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_idr{
        using Addr = Register::Address<0xfffff244,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_imr{
        using Addr = Register::Address<0xfffff248,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_isr{
        using Addr = Register::Address<0xfffff24c,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_mder{
        using Addr = Register::Address<0xfffff250,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_mddr{
        using Addr = Register::Address<0xfffff254,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_mdsr{
        using Addr = Register::Address<0xfffff258,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_pudr{
        using Addr = Register::Address<0xfffff260,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_puer{
        using Addr = Register::Address<0xfffff264,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_pusr{
        using Addr = Register::Address<0xfffff268,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_asr{
        using Addr = Register::Address<0xfffff270,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_bsr{
        using Addr = Register::Address<0xfffff274,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_absr{
        using Addr = Register::Address<0xfffff278,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_ower{
        using Addr = Register::Address<0xfffff2a0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_owdr{
        using Addr = Register::Address<0xfffff2a4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_owsr{
        using Addr = Register::Address<0xfffff2a8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> P0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(1,1)> P1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(2,2)> P2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,3)> P3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(4,4)> P4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(5,5)> P5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(6,6)> P6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,7)> P7; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(8,8)> P8; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(9,9)> P9; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(10,10)> P10; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,11)> P11; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(12,12)> P12; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(13,13)> P13; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(14,14)> P14; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,15)> P15; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(16,16)> P16; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(17,17)> P17; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(18,18)> P18; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,19)> P19; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(20,20)> P20; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(21,21)> P21; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(22,22)> P22; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,23)> P23; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(24,24)> P24; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(25,25)> P25; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(26,26)> P26; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,27)> P27; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(28,28)> P28; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(29,29)> P29; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(30,30)> P30; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,31)> P31; 
    }
    namespace PIOA_delayr0{
        using Addr = Register::Address<0xfffff2c0,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOA_delayr1{
        using Addr = Register::Address<0xfffff2c4,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOA_delayr2{
        using Addr = Register::Address<0xfffff2c8,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOA_delayr3{
        using Addr = Register::Address<0xfffff2cc,0x00000000>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(3,0)> Delay0; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(7,4)> Delay1; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(11,8)> Delay2; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(15,12)> Delay3; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(19,16)> Delay4; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,20)> Delay5; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(27,24)> Delay6; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,28)> Delay7; 
    }
    namespace PIOA_wpmr{
        using Addr = Register::Address<0xfffff2e4,0x000000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPEN; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(31,8)> WPKEY; 
    }
    namespace PIOA_wpsr{
        using Addr = Register::Address<0xfffff2e8,0xff0000fe>;
        constexpr Register::BitLocation<Addr,Register::maskFromRange(0,0)> WPVS; 
        constexpr Register::BitLocation<Addr,Register::maskFromRange(23,8)> WPVSRC; 
    }
}
