#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N0C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0C/GPBR.hpp>
