#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N1C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1C/GPBR.hpp>
