#pragma once 
#include <Chip/CM4/Atmel/ATSAM4S16B/HSMCI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/SSC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/SPI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/TC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/TC1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/TWI0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/TWI1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/PWM.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/USART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/USART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/UDP.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/ADC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/DACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/ACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/CRCCU.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/MATRIX.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/PMC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/UART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/CHIPID.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/UART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/EFC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/PIOA.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/PIOB.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/PIOC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/RSTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/SUPC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/RTT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/WDT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/RTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16B/GPBR.hpp>
