#pragma once 
#include <Chip/CM3/Atmel/ATSAM3X4E/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/SPI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TC2.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/USART3.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/UOTGHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/EMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/CAN0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/CAN1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/TRNG.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/EFC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/PIOD.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X4E/GPBR.hpp>
