#pragma once 
#include <Chip/Unknown/Atmel/ATSAMA5D31/SMD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/AXIMX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/HSMCI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SPI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SSC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/TC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/TWI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/TWI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/USART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/USART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/UART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PWM.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/LCDC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/ISI.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SFR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/HSMCI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/HSMCI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SPI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SSC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/ADC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/TWI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/USART2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/USART3.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/UART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/EMAC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/UDPHS.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/TRNG.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/FUSE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/DMAC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/DMAC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/MPDDRC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/MATRIX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/DBGU.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/AIC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIOA.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIOB.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIOC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIOD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIOE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PMC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/RSTC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SHDWC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/PIT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/WDT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/SCKC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/BSC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/GPBR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D31/RTC.hpp>
