#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N4A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4A/GPBR.hpp>
