#pragma once 
#include <Chip/CM4/Atmel/ATSAM4S8B/HSMCI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/SSC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/SPI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/TC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/TC1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/TWI0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/TWI1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/PWM.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/USART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/USART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/UDP.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/ADC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/DACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/ACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/CRCCU.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/MATRIX.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/PMC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/UART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/CHIPID.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/UART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/EFC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/PIOA.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/PIOB.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/PIOC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/RSTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/SUPC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/RTT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/WDT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/RTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S8B/GPBR.hpp>
