#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N1B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1B/GPBR.hpp>
