#pragma once 
#include <Chip/CM3/Atmel/ATSAM3SD8B/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3SD8B/GPBR.hpp>
