#pragma once 
#include <Chip/Unknown/Atmel/ATSAMA5D33/SMD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/AXIMX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/HSMCI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SPI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SSC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/TC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/TWI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/TWI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/USART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/USART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/GMAC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PWM.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/LCDC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/ISI.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SFR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/HSMCI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SPI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SSC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/ADC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/TWI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/USART2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/USART3.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/UDPHS.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/TRNG.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/FUSE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/DMAC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/DMAC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/MPDDRC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/MATRIX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/DBGU.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/AIC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIOA.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIOB.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIOC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIOD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIOE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PMC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/RSTC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SHDWC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/PIT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/WDT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/SCKC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/BSC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/GPBR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D33/RTC.hpp>
