#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S8C/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S8C/GPBR.hpp>
