#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N2A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2A/GPBR.hpp>
