#pragma once 
#include <Chip/CM3/Atmel/ATSAM3X8C/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/SPI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/UOTGHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/EMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/CAN0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/CAN1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/TRNG.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/EFC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8C/GPBR.hpp>
