#pragma once 
#include <Chip/CM4/Atmel/ATSAM4SD32B/HSMCI.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/SSC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/SPI.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/TC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/TC1.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/TWI0.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/TWI1.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/PWM.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/USART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/USART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/UDP.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/ADC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/DACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/ACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/CRCCU.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/CMCC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/MATRIX.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/PMC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/UART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/CHIPID.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/UART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/EFC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/EFC1.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/PIOA.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/PIOB.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/PIOC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/RSTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/SUPC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/RTT.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/WDT.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/RTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4SD32B/GPBR.hpp>
