#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N0A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N0A/GPBR.hpp>
