#pragma once 
#include <Chip/CM3/Atmel/ATSAM3U1E/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/USART3.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/UDPHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/ADC12B.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U1E/GPBR.hpp>
