#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S4B/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4B/GPBR.hpp>
