#pragma once 
#include <Chip/Unknown/Atmel/ATSAMA5D34/SMD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/AXIMX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/HSMCI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SPI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SSC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/CAN0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/TC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/TWI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/TWI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/USART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/USART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/GMAC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PWM.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/LCDC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/ISI.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SFR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/HSMCI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/HSMCI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SPI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SSC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/CAN1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/ADC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/TWI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/USART2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/USART3.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/UDPHS.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/TRNG.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/FUSE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/DMAC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/DMAC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/MPDDRC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/MATRIX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/DBGU.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/AIC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIOA.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIOB.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIOC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIOD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIOE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PMC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/RSTC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SHDWC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/PIT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/WDT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/SCKC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/BSC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/GPBR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D34/RTC.hpp>
