#pragma once 
#include <Chip/CM3/Atmel/ATSAM3X8E/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/SPI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TC2.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/USART3.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/UOTGHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/EMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/CAN0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/CAN1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/TRNG.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/EFC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/PIOD.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3X8E/GPBR.hpp>
