#pragma once 
#include <Chip/Unknown/Atmel/ATSAMA5D35/SMD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/AXIMX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/HSMCI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SPI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SSC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/CAN0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TWI0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TWI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/USART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/USART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/UART0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/GMAC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PWM.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/ISI.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SFR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/HSMCI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/HSMCI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SPI1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SSC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/CAN1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/ADC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TWI2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/USART2.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/USART3.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/UART1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/EMAC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/UDPHS.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/TRNG.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/FUSE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/DMAC0.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/DMAC1.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/MPDDRC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/MATRIX.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/DBGU.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/AIC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIOA.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIOB.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIOC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIOD.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIOE.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PMC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/RSTC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SHDWC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/PIT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/WDT.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/SCKC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/BSC.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/GPBR.hpp>
#include <Chip/Unknown/Atmel/ATSAMA5D35/RTC.hpp>
