#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N1A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N1A/GPBR.hpp>
