#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S1C/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1C/GPBR.hpp>
