#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S4A/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S4A/GPBR.hpp>
