#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N00A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00A/GPBR.hpp>
