#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N00B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N00B/GPBR.hpp>
