#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N4C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4C/GPBR.hpp>
