#pragma once 
#include <Chip/CM3/Atmel/ATSAM3A4C/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/SPI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/UOTGHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/CAN0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/CAN1.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/TRNG.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/EFC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3A4C/GPBR.hpp>
