#pragma once 
#include <Chip/CM4/Atmel/ATSAM4S16C/HSMCI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/SSC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/SPI.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/TC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/TC1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/TWI0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/TWI1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/PWM.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/USART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/USART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/UDP.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/ADC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/DACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/ACC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/CRCCU.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/SMC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/MATRIX.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/PMC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/UART0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/CHIPID.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/UART1.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/EFC0.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/PIOA.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/PIOB.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/PIOC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/RSTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/SUPC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/RTT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/WDT.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/RTC.hpp>
#include <Chip/CM4/Atmel/ATSAM4S16C/GPBR.hpp>
