#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N2C/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/TC1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N2C/GPBR.hpp>
