#pragma once 
#include <Chip/CM3/Atmel/ATSAM3N4B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3N4B/GPBR.hpp>
