#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S1B/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/DACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1B/GPBR.hpp>
