#pragma once 
#include <Chip/CM3/Atmel/ATSAM3S1A/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/UDP.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/ACC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/CRCCU.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/UART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/UART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/EFC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3S1A/GPBR.hpp>
