#pragma once 
#include <Chip/CM3/Atmel/ATSAM3U2E/HSMCI.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/SSC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/SPI.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/TC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/TWI0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/TWI1.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/PWM.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/USART0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/USART1.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/USART2.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/USART3.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/UDPHS.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/ADC12B.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/ADC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/DMAC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/SMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/MATRIX.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/PMC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/UART.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/CHIPID.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/EFC0.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/PIOA.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/PIOB.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/PIOC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/RSTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/SUPC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/RTT.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/WDT.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/RTC.hpp>
#include <Chip/CM3/Atmel/ATSAM3U2E/GPBR.hpp>
