#pragma once 
#include <Chip/Unknown/Nuvoton/M051_Series/ADC.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/CLK.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/EBI_CTL.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/FMC.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GCR.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP0.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP1.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP2.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP3.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP4.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GPIO.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP0_BITS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP1_BITS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP2_BITS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP3_BITS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/GP4_BITS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/I2C.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/INT.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/PWMA.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/PWMB.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/SCS.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/TMR0.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/TMR1.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/TMR2.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/TMR3.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/WDT.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/SPI0.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/SPI1.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/UART0.hpp>
#include <Chip/Unknown/Nuvoton/M051_Series/UART1.hpp>
