#pragma once 
#include <Chip/Unknown/Toshiba/M36B/SSP0.hpp>
#include <Chip/Unknown/Toshiba/M36B/SSP1.hpp>
#include <Chip/Unknown/Toshiba/M36B/SSP2.hpp>
#include <Chip/Unknown/Toshiba/M36B/UART0.hpp>
#include <Chip/Unknown/Toshiba/M36B/UART1.hpp>
#include <Chip/Unknown/Toshiba/M36B/DMAA.hpp>
#include <Chip/Unknown/Toshiba/M36B/DMAB.hpp>
#include <Chip/Unknown/Toshiba/M36B/AD.hpp>
#include <Chip/Unknown/Toshiba/M36B/EXB.hpp>
#include <Chip/Unknown/Toshiba/M36B/ADILV.hpp>
#include <Chip/Unknown/Toshiba/M36B/PA.hpp>
#include <Chip/Unknown/Toshiba/M36B/PB.hpp>
#include <Chip/Unknown/Toshiba/M36B/PC.hpp>
#include <Chip/Unknown/Toshiba/M36B/PE.hpp>
#include <Chip/Unknown/Toshiba/M36B/PF.hpp>
#include <Chip/Unknown/Toshiba/M36B/PG.hpp>
#include <Chip/Unknown/Toshiba/M36B/PH.hpp>
#include <Chip/Unknown/Toshiba/M36B/PI.hpp>
#include <Chip/Unknown/Toshiba/M36B/PJ.hpp>
#include <Chip/Unknown/Toshiba/M36B/PK.hpp>
#include <Chip/Unknown/Toshiba/M36B/PL.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB0.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB1.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB2.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB3.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB4.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB5.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB6.hpp>
#include <Chip/Unknown/Toshiba/M36B/TB7.hpp>
#include <Chip/Unknown/Toshiba/M36B/MT0.hpp>
#include <Chip/Unknown/Toshiba/M36B/MT1.hpp>
#include <Chip/Unknown/Toshiba/M36B/MT2.hpp>
#include <Chip/Unknown/Toshiba/M36B/MT3.hpp>
#include <Chip/Unknown/Toshiba/M36B/RTC.hpp>
#include <Chip/Unknown/Toshiba/M36B/SBI0.hpp>
#include <Chip/Unknown/Toshiba/M36B/SBI1.hpp>
#include <Chip/Unknown/Toshiba/M36B/SBI2.hpp>
#include <Chip/Unknown/Toshiba/M36B/SC0.hpp>
#include <Chip/Unknown/Toshiba/M36B/SC1.hpp>
#include <Chip/Unknown/Toshiba/M36B/SC2.hpp>
#include <Chip/Unknown/Toshiba/M36B/SC3.hpp>
#include <Chip/Unknown/Toshiba/M36B/RMC.hpp>
#include <Chip/Unknown/Toshiba/M36B/OFD.hpp>
#include <Chip/Unknown/Toshiba/M36B/WD.hpp>
#include <Chip/Unknown/Toshiba/M36B/CG.hpp>
#include <Chip/Unknown/Toshiba/M36B/TRMOSC.hpp>
#include <Chip/Unknown/Toshiba/M36B/LVD.hpp>
#include <Chip/Unknown/Toshiba/M36B/MTPD.hpp>
#include <Chip/Unknown/Toshiba/M36B/EN.hpp>
#include <Chip/Unknown/Toshiba/M36B/FC.hpp>
