#pragma once 
#include <Chip/Unknown/Spansion/MB9AFB4xM/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/WC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/LCDC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xM/DMAC.hpp>
