#pragma once 
#include <Chip/Unknown/Spansion/MB9AFA3xL/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/LCDC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9AFA3xL/RTC.hpp>
