#pragma once 
#include <Chip/Unknown/Spansion/MB9AF42xL/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/UNIQUE_ID.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xL/CAN1.hpp>
