#pragma once 
#include <Chip/Unknown/Spansion/MB9AF34xL/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/WC.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9AF34xL/DMAC.hpp>
