#pragma once 
#include <Chip/Unknown/Spansion/MB9AF42xK/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/UNIQUE_ID.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9AF42xK/CAN1.hpp>
