#pragma once 
#include <Chip/Unknown/Spansion/MB9AFB4xL/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/WC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/LCDC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9AFB4xL/DMAC.hpp>
