#pragma once 
#include <Chip/Unknown/Spansion/MB9AFA4xN/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/WC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/LCDC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/DS.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9AFA4xN/DMAC.hpp>
