#pragma once 
#include <Chip/Unknown/Spansion/MB9BF52xL/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/QPRC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/DS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xL/CAN1.hpp>
