#pragma once 
#include <Chip/Unknown/Fujitsu/MB9B160L/WORKFLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/FLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/UNIQUE_ID.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/ECC_CAPTURE.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/CRG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/CRTRIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/SWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/HWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DTIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFT_PPG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BTIOSEL03.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BTIOSEL47.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/SBSSR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT5.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/BT7.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/QPRC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/QPRC0_NF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/ADC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/ADC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DAC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DAC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/EXTI.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/INTREQ.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/GPIO.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/LVD.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DS.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/MFS6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/CRC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/WC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/RTC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/LCR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/CLK_GATING.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/PLL_CONTROL.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DMAC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B160L/DSTC.hpp>
