#pragma once 
#include <Chip/Unknown/Fujitsu/MB9B460R/WORKFLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/FLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/UNIQUE_ID.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/ECC_CAPTURE.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CRG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CRTRIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/SWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/HWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DTIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFT_PPG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BTIOSEL03.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BTIOSEL47.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/SBSSR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT5.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/BT7.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/QPRC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/QPRC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/QPRC0_NF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/QPRC1_NF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/ADC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/ADC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/ADC2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DAC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DAC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/EXTI.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/INTREQ.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/GPIO.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/LVD.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DS.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS5.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/MFS7.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CRC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/WC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/RTC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/LCR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CLK_GATING.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/PLL_CONTROL.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/EXBUS.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DMAC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/DSTC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CANPRES.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CAN0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/CAN1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B460R/SDIF.hpp>
