#pragma once 
#include <Chip/Unknown/Spansion/MB9BF42xS/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/UNIQUE_ID.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BTIOSEL8B.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BTIOSELCF.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT8.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT9.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT10.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT11.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT12.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT13.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT14.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/BT15.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/DS.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS8.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS9.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS10.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS11.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS12.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS13.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS14.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/MFS15.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF42xS/CAN0.hpp>
