#pragma once 
#include <Chip/Unknown/Spansion/MB9BF52xS/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/UNIQUE_ID.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BTIOSEL8B.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BTIOSELCF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT8.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT9.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT10.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT11.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT12.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT13.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT14.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/BT15.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/DS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS8.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS9.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS10.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS11.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS12.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS13.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS14.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/MFS15.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xS/CAN0.hpp>
