#pragma once 
#include <Chip/Unknown/Fujitsu/MB9B360R/WORKFLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/FLASH_IF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/UNIQUE_ID.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/ECC_CAPTURE.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/CRG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/CRTRIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/SWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/HWWDT.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DTIM.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFT_PPG.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BTIOSEL03.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BTIOSEL47.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/SBSSR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT5.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/BT7.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/QPRC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/QPRC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/QPRC0_NF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/QPRC1_NF.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/ADC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/ADC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/ADC2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DAC0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DAC1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/EXTI.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/INTREQ.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/GPIO.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/LVD.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DS.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS1.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS2.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS3.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS4.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS5.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS6.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/MFS7.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/CRC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/WC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/RTC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/LCR.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/CLK_GATING.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/PLL_CONTROL.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/EXBUS.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/USBCLK.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/USB0.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DMAC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/DSTC.hpp>
#include <Chip/Unknown/Fujitsu/MB9B360R/SDIF.hpp>
