#pragma once 
#include <Chip/Unknown/Spansion/MB9BF51xN/WORKFLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/QPRC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/QPRC2.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/ADC2.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/MFS_NFC.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CAN0.hpp>
#include <Chip/Unknown/Spansion/MB9BF51xN/CAN1.hpp>
