#pragma once 
#include <Chip/Unknown/Spansion/MB9BF52xT/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/UNIQUE_ID.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BTIOSEL8B.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BTIOSELCF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT8.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT9.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT10.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT11.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT12.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT13.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT14.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/BT15.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/QPRC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/DAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/HDMICEC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/HDMICEC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/DS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS8.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS9.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS10.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS11.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS12.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS13.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS14.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/MFS15.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/EXBUS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xT/CAN0.hpp>
