#pragma once 
#include <Chip/Unknown/Spansion/MB9BF52xK/FLASH_IF.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/CRG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/CRTRIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/SWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/HWWDT.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/DTIM.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BTIOSEL03.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BTIOSEL47.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/SBSSR.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT2.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT4.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT6.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/BT7.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/QPRC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/WC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFT_PPG.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/ADC0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/ADC1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/EXTI.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/INTREQ.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/GPIO.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/LVD.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/DS.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFS0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFS1.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFS3.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/MFS5.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/RTC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/CRC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/USBCLK.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/USB0.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/DMAC.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/CANPRES.hpp>
#include <Chip/Unknown/Spansion/MB9BF52xK/CAN1.hpp>
