#pragma once 
#include <Chip/CM4/Freescale/MK10D5/Io.hpp>
#include <Chip/CM4/Freescale/MK10D5/FTFL_FlashConfig.hpp>
#include <Chip/CM4/Freescale/MK10D5/DMA.hpp>
#include <Chip/CM4/Freescale/MK10D5/FMC.hpp>
#include <Chip/CM4/Freescale/MK10D5/FTFL.hpp>
#include <Chip/CM4/Freescale/MK10D5/DMAMUX.hpp>
#include <Chip/CM4/Freescale/MK10D5/SPI0.hpp>
#include <Chip/CM4/Freescale/MK10D5/I2S0.hpp>
#include <Chip/CM4/Freescale/MK10D5/CRC.hpp>
#include <Chip/CM4/Freescale/MK10D5/PDB0.hpp>
#include <Chip/CM4/Freescale/MK10D5/PIT.hpp>
#include <Chip/CM4/Freescale/MK10D5/FTM0.hpp>
#include <Chip/CM4/Freescale/MK10D5/FTM1.hpp>
#include <Chip/CM4/Freescale/MK10D5/ADC0.hpp>
#include <Chip/CM4/Freescale/MK10D5/RTC.hpp>
#include <Chip/CM4/Freescale/MK10D5/RFVBAT.hpp>
#include <Chip/CM4/Freescale/MK10D5/LPTMR0.hpp>
#include <Chip/CM4/Freescale/MK10D5/RFSYS.hpp>
#include <Chip/CM4/Freescale/MK10D5/TSI0.hpp>
#include <Chip/CM4/Freescale/MK10D5/SIM.hpp>
#include <Chip/CM4/Freescale/MK10D5/PORTA.hpp>
#include <Chip/CM4/Freescale/MK10D5/PORTB.hpp>
#include <Chip/CM4/Freescale/MK10D5/PORTC.hpp>
#include <Chip/CM4/Freescale/MK10D5/PORTD.hpp>
#include <Chip/CM4/Freescale/MK10D5/PORTE.hpp>
#include <Chip/CM4/Freescale/MK10D5/WDOG.hpp>
#include <Chip/CM4/Freescale/MK10D5/EWM.hpp>
#include <Chip/CM4/Freescale/MK10D5/CMT.hpp>
#include <Chip/CM4/Freescale/MK10D5/MCG.hpp>
#include <Chip/CM4/Freescale/MK10D5/OSC0.hpp>
#include <Chip/CM4/Freescale/MK10D5/I2C0.hpp>
#include <Chip/CM4/Freescale/MK10D5/UART0.hpp>
#include <Chip/CM4/Freescale/MK10D5/UART1.hpp>
#include <Chip/CM4/Freescale/MK10D5/UART2.hpp>
#include <Chip/CM4/Freescale/MK10D5/CMP0.hpp>
#include <Chip/CM4/Freescale/MK10D5/CMP1.hpp>
#include <Chip/CM4/Freescale/MK10D5/VREF.hpp>
#include <Chip/CM4/Freescale/MK10D5/LLWU.hpp>
#include <Chip/CM4/Freescale/MK10D5/PMC.hpp>
#include <Chip/CM4/Freescale/MK10D5/SMC.hpp>
#include <Chip/CM4/Freescale/MK10D5/RCM.hpp>
#include <Chip/CM4/Freescale/MK10D5/PTA.hpp>
#include <Chip/CM4/Freescale/MK10D5/PTB.hpp>
#include <Chip/CM4/Freescale/MK10D5/PTC.hpp>
#include <Chip/CM4/Freescale/MK10D5/PTD.hpp>
#include <Chip/CM4/Freescale/MK10D5/PTE.hpp>
#include <Chip/CM4/Freescale/MK10D5/SystemControl.hpp>
#include <Chip/CM4/Freescale/MK10D5/SysTick.hpp>
#include <Chip/CM4/Freescale/MK10D5/NVIC.hpp>
