#pragma once 
#include <Chip/CM4/Freescale/MK11D5/Io.hpp>
#include <Chip/CM4/Freescale/MK11D5/FTFL_FlashConfig.hpp>
#include <Chip/CM4/Freescale/MK11D5/DMA.hpp>
#include <Chip/CM4/Freescale/MK11D5/FMC.hpp>
#include <Chip/CM4/Freescale/MK11D5/FTFL.hpp>
#include <Chip/CM4/Freescale/MK11D5/DMAMUX.hpp>
#include <Chip/CM4/Freescale/MK11D5/RNG.hpp>
#include <Chip/CM4/Freescale/MK11D5/SPI0.hpp>
#include <Chip/CM4/Freescale/MK11D5/SPI1.hpp>
#include <Chip/CM4/Freescale/MK11D5/I2S0.hpp>
#include <Chip/CM4/Freescale/MK11D5/CRC.hpp>
#include <Chip/CM4/Freescale/MK11D5/PDB0.hpp>
#include <Chip/CM4/Freescale/MK11D5/PIT.hpp>
#include <Chip/CM4/Freescale/MK11D5/FTM0.hpp>
#include <Chip/CM4/Freescale/MK11D5/FTM1.hpp>
#include <Chip/CM4/Freescale/MK11D5/FTM2.hpp>
#include <Chip/CM4/Freescale/MK11D5/ADC0.hpp>
#include <Chip/CM4/Freescale/MK11D5/RTC.hpp>
#include <Chip/CM4/Freescale/MK11D5/RFVBAT.hpp>
#include <Chip/CM4/Freescale/MK11D5/DAC0.hpp>
#include <Chip/CM4/Freescale/MK11D5/LPTMR0.hpp>
#include <Chip/CM4/Freescale/MK11D5/RFSYS.hpp>
#include <Chip/CM4/Freescale/MK11D5/SIM.hpp>
#include <Chip/CM4/Freescale/MK11D5/PORTA.hpp>
#include <Chip/CM4/Freescale/MK11D5/PORTB.hpp>
#include <Chip/CM4/Freescale/MK11D5/PORTC.hpp>
#include <Chip/CM4/Freescale/MK11D5/PORTD.hpp>
#include <Chip/CM4/Freescale/MK11D5/PORTE.hpp>
#include <Chip/CM4/Freescale/MK11D5/WDOG.hpp>
#include <Chip/CM4/Freescale/MK11D5/EWM.hpp>
#include <Chip/CM4/Freescale/MK11D5/CMT.hpp>
#include <Chip/CM4/Freescale/MK11D5/MCG.hpp>
#include <Chip/CM4/Freescale/MK11D5/OSC.hpp>
#include <Chip/CM4/Freescale/MK11D5/I2C0.hpp>
#include <Chip/CM4/Freescale/MK11D5/I2C1.hpp>
#include <Chip/CM4/Freescale/MK11D5/UART0.hpp>
#include <Chip/CM4/Freescale/MK11D5/UART1.hpp>
#include <Chip/CM4/Freescale/MK11D5/UART2.hpp>
#include <Chip/CM4/Freescale/MK11D5/UART3.hpp>
#include <Chip/CM4/Freescale/MK11D5/CMP0.hpp>
#include <Chip/CM4/Freescale/MK11D5/CMP1.hpp>
#include <Chip/CM4/Freescale/MK11D5/VREF.hpp>
#include <Chip/CM4/Freescale/MK11D5/LLWU.hpp>
#include <Chip/CM4/Freescale/MK11D5/PMC.hpp>
#include <Chip/CM4/Freescale/MK11D5/SMC.hpp>
#include <Chip/CM4/Freescale/MK11D5/RCM.hpp>
#include <Chip/CM4/Freescale/MK11D5/GPIOA.hpp>
#include <Chip/CM4/Freescale/MK11D5/GPIOB.hpp>
#include <Chip/CM4/Freescale/MK11D5/GPIOC.hpp>
#include <Chip/CM4/Freescale/MK11D5/GPIOD.hpp>
#include <Chip/CM4/Freescale/MK11D5/GPIOE.hpp>
#include <Chip/CM4/Freescale/MK11D5/SystemControl.hpp>
#include <Chip/CM4/Freescale/MK11D5/SysTick.hpp>
#include <Chip/CM4/Freescale/MK11D5/NVIC.hpp>
#include <Chip/CM4/Freescale/MK11D5/MCM.hpp>
#include <Chip/CM4/Freescale/MK11D5/CAU.hpp>
