#pragma once 
#include <Chip/CM4/Freescale/MK21D5/Io.hpp>
#include <Chip/CM4/Freescale/MK21D5/FTFL_FlashConfig.hpp>
#include <Chip/CM4/Freescale/MK21D5/DMA.hpp>
#include <Chip/CM4/Freescale/MK21D5/FMC.hpp>
#include <Chip/CM4/Freescale/MK21D5/FTFL.hpp>
#include <Chip/CM4/Freescale/MK21D5/DMAMUX.hpp>
#include <Chip/CM4/Freescale/MK21D5/RNG.hpp>
#include <Chip/CM4/Freescale/MK21D5/SPI0.hpp>
#include <Chip/CM4/Freescale/MK21D5/SPI1.hpp>
#include <Chip/CM4/Freescale/MK21D5/I2S0.hpp>
#include <Chip/CM4/Freescale/MK21D5/CRC.hpp>
#include <Chip/CM4/Freescale/MK21D5/USBDCD.hpp>
#include <Chip/CM4/Freescale/MK21D5/PDB0.hpp>
#include <Chip/CM4/Freescale/MK21D5/PIT.hpp>
#include <Chip/CM4/Freescale/MK21D5/FTM0.hpp>
#include <Chip/CM4/Freescale/MK21D5/FTM1.hpp>
#include <Chip/CM4/Freescale/MK21D5/FTM2.hpp>
#include <Chip/CM4/Freescale/MK21D5/ADC0.hpp>
#include <Chip/CM4/Freescale/MK21D5/RTC.hpp>
#include <Chip/CM4/Freescale/MK21D5/RFVBAT.hpp>
#include <Chip/CM4/Freescale/MK21D5/DAC0.hpp>
#include <Chip/CM4/Freescale/MK21D5/LPTMR0.hpp>
#include <Chip/CM4/Freescale/MK21D5/RFSYS.hpp>
#include <Chip/CM4/Freescale/MK21D5/SIM.hpp>
#include <Chip/CM4/Freescale/MK21D5/PORTA.hpp>
#include <Chip/CM4/Freescale/MK21D5/PORTB.hpp>
#include <Chip/CM4/Freescale/MK21D5/PORTC.hpp>
#include <Chip/CM4/Freescale/MK21D5/PORTD.hpp>
#include <Chip/CM4/Freescale/MK21D5/PORTE.hpp>
#include <Chip/CM4/Freescale/MK21D5/WDOG.hpp>
#include <Chip/CM4/Freescale/MK21D5/EWM.hpp>
#include <Chip/CM4/Freescale/MK21D5/CMT.hpp>
#include <Chip/CM4/Freescale/MK21D5/MCG.hpp>
#include <Chip/CM4/Freescale/MK21D5/OSC.hpp>
#include <Chip/CM4/Freescale/MK21D5/I2C0.hpp>
#include <Chip/CM4/Freescale/MK21D5/I2C1.hpp>
#include <Chip/CM4/Freescale/MK21D5/UART0.hpp>
#include <Chip/CM4/Freescale/MK21D5/UART1.hpp>
#include <Chip/CM4/Freescale/MK21D5/UART2.hpp>
#include <Chip/CM4/Freescale/MK21D5/UART3.hpp>
#include <Chip/CM4/Freescale/MK21D5/USB0.hpp>
#include <Chip/CM4/Freescale/MK21D5/CMP0.hpp>
#include <Chip/CM4/Freescale/MK21D5/CMP1.hpp>
#include <Chip/CM4/Freescale/MK21D5/VREF.hpp>
#include <Chip/CM4/Freescale/MK21D5/LLWU.hpp>
#include <Chip/CM4/Freescale/MK21D5/PMC.hpp>
#include <Chip/CM4/Freescale/MK21D5/SMC.hpp>
#include <Chip/CM4/Freescale/MK21D5/RCM.hpp>
#include <Chip/CM4/Freescale/MK21D5/GPIOA.hpp>
#include <Chip/CM4/Freescale/MK21D5/GPIOB.hpp>
#include <Chip/CM4/Freescale/MK21D5/GPIOC.hpp>
#include <Chip/CM4/Freescale/MK21D5/GPIOD.hpp>
#include <Chip/CM4/Freescale/MK21D5/GPIOE.hpp>
#include <Chip/CM4/Freescale/MK21D5/SystemControl.hpp>
#include <Chip/CM4/Freescale/MK21D5/SysTick.hpp>
#include <Chip/CM4/Freescale/MK21D5/NVIC.hpp>
#include <Chip/CM4/Freescale/MK21D5/MCM.hpp>
#include <Chip/CM4/Freescale/MK21D5/CAU.hpp>
