#pragma once 
#include <Chip/CM0+/Freescale/MKL04Z4/FTFA_FlashConfig.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/DMA.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/FTFA.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/DMAMUX0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/PIT.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/TPM0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/TPM1.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/ADC0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/RTC.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/LPTMR0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/SIM.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/PORTA.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/PORTB.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/MCG.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/OSC0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/I2C0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/UART0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/CMP0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/SPI0.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/LLWU.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/PMC.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/SMC.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/RCM.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/GPIOA.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/GPIOB.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/SystemControl.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/SysTick.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/NVIC.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/MTB.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/MTBDWT.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/ROM.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/MCM.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/FGPIOA.hpp>
#include <Chip/CM0+/Freescale/MKL04Z4/FGPIOB.hpp>
