#pragma once 
#include <Chip/CM4/Nordic/nrf52/FICR.hpp>
#include <Chip/CM4/Nordic/nrf52/UICR.hpp>
#include <Chip/CM4/Nordic/nrf52/BPROT.hpp>
#include <Chip/CM4/Nordic/nrf52/POWER.hpp>
#include <Chip/CM4/Nordic/nrf52/CLOCK.hpp>
#include <Chip/CM4/Nordic/nrf52/RADIO.hpp>
#include <Chip/CM4/Nordic/nrf52/UARTE0.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIM0.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIS0.hpp>
#include <Chip/CM4/Nordic/nrf52/TWIM0.hpp>
#include <Chip/CM4/Nordic/nrf52/TWIS0.hpp>
#include <Chip/CM4/Nordic/nrf52/SPI0.hpp>
#include <Chip/CM4/Nordic/nrf52/TWI0.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIM1.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIS1.hpp>
#include <Chip/CM4/Nordic/nrf52/TWIM1.hpp>
#include <Chip/CM4/Nordic/nrf52/TWIS1.hpp>
#include <Chip/CM4/Nordic/nrf52/SPI1.hpp>
#include <Chip/CM4/Nordic/nrf52/NFCT.hpp>
#include <Chip/CM4/Nordic/nrf52/GPIOTE.hpp>
#include <Chip/CM4/Nordic/nrf52/SAADC.hpp>
#include <Chip/CM4/Nordic/nrf52/TIMER0.hpp>
#include <Chip/CM4/Nordic/nrf52/TIMER1.hpp>
#include <Chip/CM4/Nordic/nrf52/TIMER2.hpp>
#include <Chip/CM4/Nordic/nrf52/RTC0.hpp>
#include <Chip/CM4/Nordic/nrf52/TEMP.hpp>
#include <Chip/CM4/Nordic/nrf52/RNG.hpp>
#include <Chip/CM4/Nordic/nrf52/ECB.hpp>
#include <Chip/CM4/Nordic/nrf52/CCM.hpp>
#include <Chip/CM4/Nordic/nrf52/AAR.hpp>
#include <Chip/CM4/Nordic/nrf52/WDT.hpp>
#include <Chip/CM4/Nordic/nrf52/RTC1.hpp>
#include <Chip/CM4/Nordic/nrf52/QDEC.hpp>
#include <Chip/CM4/Nordic/nrf52/COMP.hpp>
#include <Chip/CM4/Nordic/nrf52/LPCOMP.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI0.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU0.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI1.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU1.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI2.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU2.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI3.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU3.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI4.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU4.hpp>
#include <Chip/CM4/Nordic/nrf52/SWI5.hpp>
#include <Chip/CM4/Nordic/nrf52/EGU5.hpp>
#include <Chip/CM4/Nordic/nrf52/TIMER3.hpp>
#include <Chip/CM4/Nordic/nrf52/TIMER4.hpp>
#include <Chip/CM4/Nordic/nrf52/PWM0.hpp>
#include <Chip/CM4/Nordic/nrf52/PDM.hpp>
#include <Chip/CM4/Nordic/nrf52/NVMC.hpp>
#include <Chip/CM4/Nordic/nrf52/PPI.hpp>
#include <Chip/CM4/Nordic/nrf52/MWU.hpp>
#include <Chip/CM4/Nordic/nrf52/PWM1.hpp>
#include <Chip/CM4/Nordic/nrf52/PWM2.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIM2.hpp>
#include <Chip/CM4/Nordic/nrf52/SPIS2.hpp>
#include <Chip/CM4/Nordic/nrf52/SPI2.hpp>
#include <Chip/CM4/Nordic/nrf52/RTC2.hpp>
#include <Chip/CM4/Nordic/nrf52/I2S.hpp>
#include <Chip/CM4/Nordic/nrf52/P0.hpp>
#include <Chip/CM4/Nordic/nrf52/TWI1.hpp>
#include <Chip/CM4/Nordic/nrf52/UART0.hpp>
