#pragma once 
#include <Chip/CM0/Nordic/nrf51/POWER.hpp>
#include <Chip/CM0/Nordic/nrf51/CLOCK.hpp>
#include <Chip/CM0/Nordic/nrf51/MPU.hpp>
#include <Chip/CM0/Nordic/nrf51/AMLI.hpp>
#include <Chip/CM0/Nordic/nrf51/RADIO.hpp>
#include <Chip/CM0/Nordic/nrf51/UART0.hpp>
#include <Chip/CM0/Nordic/nrf51/SPI0.hpp>
#include <Chip/CM0/Nordic/nrf51/TWI0.hpp>
#include <Chip/CM0/Nordic/nrf51/SPI1.hpp>
#include <Chip/CM0/Nordic/nrf51/TWI1.hpp>
#include <Chip/CM0/Nordic/nrf51/SPIS1.hpp>
#include <Chip/CM0/Nordic/nrf51/SPIM1.hpp>
#include <Chip/CM0/Nordic/nrf51/GPIOTE.hpp>
#include <Chip/CM0/Nordic/nrf51/ADC.hpp>
#include <Chip/CM0/Nordic/nrf51/TIMER0.hpp>
#include <Chip/CM0/Nordic/nrf51/TIMER1.hpp>
#include <Chip/CM0/Nordic/nrf51/TIMER2.hpp>
#include <Chip/CM0/Nordic/nrf51/RTC0.hpp>
#include <Chip/CM0/Nordic/nrf51/TEMP.hpp>
#include <Chip/CM0/Nordic/nrf51/RNG.hpp>
#include <Chip/CM0/Nordic/nrf51/ECB.hpp>
#include <Chip/CM0/Nordic/nrf51/AAR.hpp>
#include <Chip/CM0/Nordic/nrf51/CCM.hpp>
#include <Chip/CM0/Nordic/nrf51/WDT.hpp>
#include <Chip/CM0/Nordic/nrf51/RTC1.hpp>
#include <Chip/CM0/Nordic/nrf51/QDEC.hpp>
#include <Chip/CM0/Nordic/nrf51/LPCOMP.hpp>
#include <Chip/CM0/Nordic/nrf51/SWI.hpp>
#include <Chip/CM0/Nordic/nrf51/NVMC.hpp>
#include <Chip/CM0/Nordic/nrf51/PPI.hpp>
#include <Chip/CM0/Nordic/nrf51/FICR.hpp>
#include <Chip/CM0/Nordic/nrf51/UICR.hpp>
#include <Chip/CM0/Nordic/nrf51/GPIO.hpp>
