#pragma once 
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SARADC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SARADC_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/AES_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/CRC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/CAPSENSE_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/CLKCTRL_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/CMP_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/CMP_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/DMACTRL_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/DMAXBAR_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/DEVICEID_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/EPCA_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/FLASHCTRL_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/I2C_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/I2C_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/I2S_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/IDAC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/IDAC_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/IVC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/LOCK_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/LPTIMER_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PLL_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/EXTOSC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/LPOSC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PCA_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PCA_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PMU_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBCFG_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBHD_4.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBSTD_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBSTD_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBSTD_2.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/PBSTD_3.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/RTC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/RSTSRC_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SPI_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SPI_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SPI_2.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/SSG_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/TIMER_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/TIMER_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/UART_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/UART_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/USART_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/USART_1.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/VMON_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/VREF_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/EXTVREG_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/VREG_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/LDO_0.hpp>
#include <Chip/Unknown/SiliconLabs/SIM3C1x4_SVD/WDTIMER_0.hpp>
