#pragma once 
#include <Chip/CM0+/Freescale/SKEAZN642/FTMRH_FlashConfig.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FTMRH.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/IRQ.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/CRC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/PIT.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FTM0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FTM1.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FTM2.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/ADC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/RTC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/SIM.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/PORT.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/WDOG.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/ICS.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/OSC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/I2C0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/UART0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/UART1.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/UART2.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/ACMP0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/ACMP1.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/SPI0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/SPI1.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/KBI0.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/KBI1.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/PMC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/GPIOA.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/GPIOB.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/SystemControl.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/SysTick.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/NVIC.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/ROM.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/MCM.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FGPIOA.hpp>
#include <Chip/CM0+/Freescale/SKEAZN642/FGPIOB.hpp>
