#pragma once 
#include <Chip/Unknown/STMicro/STM32F40x/RNG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/DCMI.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/FSMC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/DBG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOI.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/I2S2ext.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/I2S3ext.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/SDIO.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/ADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/ADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/ADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/USART6.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/I2C3.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/C_ADC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM8.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/Ethernet_MAC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/Ethernet_MMC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/Ethernet_PTP.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/Ethernet_DMA.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_FS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_FS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_FS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_FS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/CAN1.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/CAN2.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/FLASH.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_HS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_HS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_HS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/OTG_HS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F40x/NVIC.hpp>
