#pragma once 
#include <Chip/Unknown/STMicro/STM32F41x/RNG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/HASH.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/CRYP.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/DCMI.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/FSMC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/DBG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOI.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/I2S2ext.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/I2S3ext.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/SDIO.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/ADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/ADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/ADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/USART6.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/I2C3.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/C_ADC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM8.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/Ethernet_MAC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/Ethernet_MMC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/Ethernet_PTP.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/Ethernet_DMA.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_FS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_FS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_FS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_FS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/CAN1.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/CAN2.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/NVIC.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/FLASH.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_HS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_HS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_HS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F41x/OTG_HS_PWRCLK.hpp>
