#pragma once 
#include <Chip/Unknown/STMicro/STM32L1xx/AES.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/C_ADC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/COMP.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/Flash.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/FSMC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/LCD.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/OPAMP.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/RI.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/SDIO.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/USB.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/USB_SRAM.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/ADC.hpp>
#include <Chip/Unknown/STMicro/STM32L1xx/NVIC.hpp>
