#pragma once 
#include <Chip/Unknown/STMicro/STM32F20x/RNG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/DCMI.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/FSMC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/DBG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOI.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/SDIO.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/ADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/ADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/ADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/USART6.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/CAN2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/CAN1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/I2C3.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/ADC_Common.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM8.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/Ethernet_MAC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/Ethernet_MMC.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/Ethernet_PTP.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/Ethernet_DMA.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_FS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_FS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_FS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_FS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/FLASH.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_HS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_HS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_HS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/OTG_HS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F20x/NVIC.hpp>
