#pragma once 
#include <Chip/Unknown/STMicro/STM32F21x/RNG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/DCMI.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/FSMC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/DBG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOI.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/SDIO.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/ADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/ADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/ADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/USART6.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/CAN2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/CAN1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/I2C3.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/ADC_Common.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM8.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/Ethernet_MAC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/Ethernet_MMC.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/Ethernet_PTP.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/Ethernet_DMA.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_FS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_FS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_FS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_FS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/FLASH.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/HASH.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/CRYP.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_HS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_HS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_HS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/OTG_HS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F21x/NVIC.hpp>
