#pragma once 
#include <Chip/Unknown/STMicro/STM32F37x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TSC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/Flash.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM19.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM15.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM16.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM17.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/I2S2ext.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/I2S3ext.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/ADC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/COMP.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/CEC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/CAN.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/USB.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SDADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SDADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/SDADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/DAC2.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM18.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/DAC1.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/NVIC.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/FPU.hpp>
#include <Chip/Unknown/STMicro/STM32F37x/DBGMCU.hpp>
